---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

litellm:
  enabled: true
  db:
    deployStandalone: false
opensearch:
  enabled: true

---

config:
  API_HOST: ""
  FRONT_HOST: ""
  DEMO_PROMPT_KEEPER_API_HOST: ""
  DEMO_PROMPT_KEEPER_FRONT_HOST: ""

# defaultPodOptions:
#   automountServiceAccountToken: false
#   securityContext:
#     fsGroup: 1001
#     fsGroupChangePolicy: "OnRootMismatch"
#     runAsGroup: 1001
#     runAsNonRoot: true
#     runAsUser: 1001
#     seccompProfile:
#       type: RuntimeDefault
#     seLinuxOptions: {}

defaultContainerSecurityContext: &defaultContainerSecurityContext
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true

controllers:
  prompt-keeper:
    enabled: true
    type: deployment
    strategy: RollingUpdate
    revisionHistoryLimit: 20
    containers:
      main:
        image:
          repository : "kinorai/prompt-keeper"
          tag: "1"
          pullPolicy: Always
        env:
          - name: API_BASE_URL
            value: "http://{{.Release.Name}}-api.{{.Release.Namespace}}.svc.cluster.local:8000"
        envFrom:
          - secret: prompt-keeper
        ports:
          - containerPort: 3000
        resources: {}
        # resources:
        #   requests:
        #     cpu: 10m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 256Mi
        probes:
          liveness:
            enabled: true
            spec:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 5
          readiness:
            enabled: true
            spec:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 5
        # Additional security hardening for nginx
        # securityContext: *defaultContainerSecurityContext

service:
  prompt-keeper:
    enabled: true
    controller: prompt-keeper
    type: ClusterIP
    ports:
      http:
        port: 3000

ingress: []

secrets:
  # Secrets are used instead of ConfigMaps because pods are automatically reloaded when Secrets change, unlike ConfigMaps
  prompt-keeper:
    enabled: true
    stringData:
      LOG_LEVEL: "debug"
      OPENAI_API_KEY: ""
      OPENAI_API_BASE: ""
      OR_APP_NAME: "Prompt Keeper LiteLLM"
      ANTHROPIC_API_KEY: ""
      LITELLM_MASTER_KEY: "sk-1234"
      # OpenSearch
      OPENSEARCH_HOST: "http://{{ .Release.Name }}-opensearch.{{ .Release.Namespace }}.svc.cluster.local:9200"
      OPENSEARCH_USERNAME: "admin"
      OPENSEARCH_PASSWORD: "adminadminA2!^eaA325153!!*"
      OPENSEARCH_INDEX: "litellm"
      OPENSEARCH_INDEX_SETTINGS: "{}"

