---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

litellm:
  enabled: true
  db:
    deployStandalone: false
  environmentSecrets:
    - prompt-keeper-litellm
  proxy_config:
    model_list:
  # Use this if you want to make requests to `claude-3-haiku-20240307`,`claude-3-opus-20240229`,`claude-2.1` without defining them on the config.yaml
  # Default models
  # Works for ALL Providers and needs the default provider credentials in .env
    - model_name: "*"
      litellm_params:
        model: openai/*
        api_key: os.environ/OPENAI_API_KEY
    - model_name: "*"
      litellm_params:
        model: anthropic/*
        api_key: os.environ/ANTHROPIC_API_KEY
    - model_name: "*"
      litellm_params:
        model: deepseek/*
        api_key: os.environ/DEEPSEEK_API_KEY
    - model_name: "*"
      litellm_params:
        model: gemini/*
        api_key: os.environ/GEMINI_API_KEY
    # - model_name: "*"
    #   litellm_params:
    #     model: archipels-svc/*
    #     api_key: os.environ/ARCHIPELS_API_KEY
    #     api_base: os.environ/ARCHIPELS_API_BASE

opensearch:
  enabled: true
  master:
    masterOnly: false
    replicaCount: 1
    extraEnvVarsSecret: "prompt-keeper-opensearch"
  data:
    replicaCount: 1
  coordinating:
    replicaCount: 1
  ingest:
    replicaCount: 1

config:
  API_HOST: ""
  FRONT_HOST: ""
  DEMO_PROMPT_KEEPER_API_HOST: ""
  DEMO_PROMPT_KEEPER_FRONT_HOST: ""

# defaultPodOptions:
#   automountServiceAccountToken: false
#   securityContext:
#     fsGroup: 1001
#     fsGroupChangePolicy: "OnRootMismatch"
#     runAsGroup: 1001
#     runAsNonRoot: true
#     runAsUser: 1001
#     seccompProfile:
#       type: RuntimeDefault
#     seLinuxOptions: {}

defaultContainerSecurityContext: &defaultContainerSecurityContext
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true

controllers:
  prompt-keeper:
    enabled: true
    type: deployment
    strategy: RollingUpdate
    revisionHistoryLimit: 20
    containers:
      main:
        image:
          repository : "kinorai/prompt-keeper"
          tag: "1"
          pullPolicy: Always
        env:
          - name: API_BASE_URL
            value: "http://{{.Release.Name}}-api.{{.Release.Namespace}}.svc.cluster.local:8000"
        envFrom:
          - secret: api
          - secret: common
          - secret: opensearch
        ports:
          - containerPort: 3000
        resources: {}
        # resources:
        #   requests:
        #     cpu: 10m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 256Mi
        probes:
          liveness:
            enabled: true
            spec:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 5
          readiness:
            enabled: true
            spec:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 5
        # Additional security hardening for nginx
        # securityContext: *defaultContainerSecurityContext

service:
  prompt-keeper:
    enabled: true
    controller: prompt-keeper
    type: ClusterIP
    ports:
      http:
        port: 3000

ingress: []

secrets:
  api:
    enabled: true
    stringData:
      OPENSEARCH_HOST: "http://{{ .Release.Name }}-opensearch.{{ .Release.Namespace }}.svc.cluster.local:9200"
      OPENSEARCH_INDEX: "litellm"
      OPENSEARCH_INDEX_SETTINGS: "{}"
  # Secrets are used instead of ConfigMaps because pods are automatically reloaded when Secrets change, unlike ConfigMaps
  common:
    enabled: true
    stringData:
      LOG_LEVEL: "debug"
  # LiteLLM
  litellm:
    enabled: true
    stringData:
      OR_APP_NAME: "Prompt Keeper LiteLLM"
      LITELLM_MASTER_KEY: "sk-1234"
      OPENAI_API_KEY: "sk-1234"
      ANTHROPIC_API_KEY: "sk-1234"
      DEEPSEEK_API_KEY: "sk-1234"
      GEMINI_API_KEY: "sk-1234"
      ARCHIPELS_API_KEY: "sk-1234"
      ARCHIPELS_API_BASE: "https://chat.svc.archipels.io/api"
      # OpenSearch
  opensearch:
    enabled: true
    stringData:
      OPENSEARCH_USERNAME: "azkjfaegfeiaufnjoiahj"
      OPENSEARCH_PASSWORD: "adminadminA2!^eaA325153!!*"
