# Add 'frontend' label to any changes in frontend files
frontend:
- changed-files:
    any-glob-to-any-file:
      - src/app/**/*
      - '!src/app/api/**/*'
      - src/components/**/*
      - src/lib/hooks/**/*
      - src/styles/**/*
      - src/**/*.css

# Add 'backend' label to any change in backend files
backend:
- changed-files:
    any-glob-to-any-file:
      - src/api/**/*
      - src/lib/**/*
      - src/server/**/*

# Add 'documentation' label to any change in documentation
documentation:
- changed-files:
    any-glob-to-any-file:
      - '**/*.md'
      - docs/**/*

# Add 'dependencies' label to any change in package files
dependencies:
- changed-files:
    any-glob-to-any-file:
      - package.json
      - package-lock.json
      - yarn.lock
      - pnpm-lock.yaml

# Add 'configuration' label to any change in config files
configuration:
- changed-files:
    any-glob-to-any-file:
      - '*.js'
      - '*.ts'
      - '*.json'
      - '*ignore'
      - '*.yaml'
      - '*.yml'
      - .env*
      - .github/**/*

# Add 'test' label to any change in test files
test:
- changed-files:
    any-glob-to-any-file:
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'
      - src/__tests__/**/*
      - jest.config.js
      - jest.setup.ts

# Add 'security' label to any change in security-related files
security:
- changed-files:
    any-glob-to-any-file:
      - '**/security/**/*'
      - '**/auth/**/*'
      - src/middleware.ts
