changelog:
  exclude:
    labels:
      - "ignore-for-release"
    authors:
      - "octocat" # You might want to change or remove this
  categories:
    - title: "Breaking Changes 🛠"
      labels:
        - "Semver-Major"
        - "breaking-change"
    - title: "Exciting New Features 🎉"
      labels:
        - "Semver-Minor"
        - "enhancement"
    - title: "Bug Fixes 🐛"
      labels:
        - "bug"
        - "fix"
    - title: "Documentation 📄"
      labels:
        - "documentation"
    - title: "Dependency Updates ⬆️"
      labels:
        - "dependencies"
    - title: "Other Changes"
      labels:
        - "*"
