annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: |-
        Only add hostUsers when explicitly configured
    - kind: fixed
      description: |-
        `hosts` should be an optional field for Ingress resources
    - kind: fixed
      description: |-
        `defaultBackend` should be an object for Ingress resources
apiVersion: v2
description: Function library for Helm charts
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
keywords:
- common
- library
kubeVersion: '>=1.22.0-0'
maintainers:
- email: me@bjw-s.dev
  name: bjw-s
name: common
type: library
version: 3.6.1
